app:
  payment-service:
    baseUrl: http://localhost:9191/payments

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shoppingcart?useSSL=false&serverTimezone=UTC&autoReconnect=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


management:
  tracing:
    propagation: 
      type: B3
    sampling:
      probability: 1.0
    enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    health:
      enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  #zipkin:
  #  tracing:
  #    endpoint: http://localhost:9411/

  #zipkin:
  #  tracing:
  #    baseUrl: http://127.0.0.1:9411/zipkin/
